<?php

class RegionsTableSeeder extends Seeder {

	public function run()
	{
        $region = new Region();
        $region->name           = 'Ethiopia';
        $region->description    = 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Maecenas malesuada, metus eget condimentum consectetur, purus velit aliquam quam, ac ullamcorper tellus nisl vulputate nibh. Maecenas iaculis, justo id varius pellentesque, nunc tortor dapibus sem, ut malesuada leo diam in urna. Donec nibh magna, blandit eget magna hendrerit, tincidunt mollis magna. Proin dapibus massa a nibh ultrices tempus. Praesent sed fringilla massa. Quisque quis lobortis ipsum. Suspendisse ut ex nisl. Cras sit amet urna tempor, porttitor libero ac, rhoncus libero. Etiam nec purus at turpis semper aliquet vitae quis quam. Morbi sodales urna vel neque vestibulum placerat.
                                   Quisque aliquet, nisl quis sagittis porta, nibh ipsum sagittis leo, eu aliquet orci sapien ut velit. Praesent vel condimentum nisi, ac tristique mi. Sed eu nulla accumsan, commodo tortor at, egestas mi. Proin eros sem, porta nec accumsan gravida, imperdiet non tellus. Sed egestas, ex sed tristique finibus, arcu diam ultricies ligula, eu aliquet tortor ex quis tortor. Curabitur vitae mattis leo. Phasellus tristique, sem vitae egestas porttitor, neque mi rutrum nisi, sit amet feugiat neque eros quis purus. Proin sed turpis vitae magna egestas mollis a eget massa. Nam magna orci, accumsan ac luctus quis, egestas a dui. Suspendisse potenti. Aenean vestibulum libero magna, ut egestas erat rutrum porttitor. Vivamus eu suscipit leo. Sed fermentum non leo tempus faucibus. Aenean dolor turpis, finibus in imperdiet ac, viverra volutpat risus. Praesent quis auctor mauris.';
        $region->img_url        = 'PLACEHOLDER';
        $region->save();

        $region = new Region();
        $region->name           = 'Kenya';
        $region->description    = 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Maecenas malesuada, metus eget condimentum consectetur, purus velit aliquam quam, ac ullamcorper tellus nisl vulputate nibh. Maecenas iaculis, justo id varius pellentesque, nunc tortor dapibus sem, ut malesuada leo diam in urna. Donec nibh magna, blandit eget magna hendrerit, tincidunt mollis magna. Proin dapibus massa a nibh ultrices tempus. Praesent sed fringilla massa. Quisque quis lobortis ipsum. Suspendisse ut ex nisl. Cras sit amet urna tempor, porttitor libero ac, rhoncus libero. Etiam nec purus at turpis semper aliquet vitae quis quam. Morbi sodales urna vel neque vestibulum placerat.
                                   Quisque aliquet, nisl quis sagittis porta, nibh ipsum sagittis leo, eu aliquet orci sapien ut velit. Praesent vel condimentum nisi, ac tristique mi. Sed eu nulla accumsan, commodo tortor at, egestas mi. Proin eros sem, porta nec accumsan gravida, imperdiet non tellus. Sed egestas, ex sed tristique finibus, arcu diam ultricies ligula, eu aliquet tortor ex quis tortor. Curabitur vitae mattis leo. Phasellus tristique, sem vitae egestas porttitor, neque mi rutrum nisi, sit amet feugiat neque eros quis purus. Proin sed turpis vitae magna egestas mollis a eget massa. Nam magna orci, accumsan ac luctus quis, egestas a dui. Suspendisse potenti. Aenean vestibulum libero magna, ut egestas erat rutrum porttitor. Vivamus eu suscipit leo. Sed fermentum non leo tempus faucibus. Aenean dolor turpis, finibus in imperdiet ac, viverra volutpat risus. Praesent quis auctor mauris.';
        $region->img_url        = 'PLACEHOLDER';
        $region->save();

        $region = new Region();
        $region->name           = 'El Salvador';
        $region->description    = 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Maecenas malesuada, metus eget condimentum consectetur, purus velit aliquam quam, ac ullamcorper tellus nisl vulputate nibh. Maecenas iaculis, justo id varius pellentesque, nunc tortor dapibus sem, ut malesuada leo diam in urna. Donec nibh magna, blandit eget magna hendrerit, tincidunt mollis magna. Proin dapibus massa a nibh ultrices tempus. Praesent sed fringilla massa. Quisque quis lobortis ipsum. Suspendisse ut ex nisl. Cras sit amet urna tempor, porttitor libero ac, rhoncus libero. Etiam nec purus at turpis semper aliquet vitae quis quam. Morbi sodales urna vel neque vestibulum placerat.
                                   Quisque aliquet, nisl quis sagittis porta, nibh ipsum sagittis leo, eu aliquet orci sapien ut velit. Praesent vel condimentum nisi, ac tristique mi. Sed eu nulla accumsan, commodo tortor at, egestas mi. Proin eros sem, porta nec accumsan gravida, imperdiet non tellus. Sed egestas, ex sed tristique finibus, arcu diam ultricies ligula, eu aliquet tortor ex quis tortor. Curabitur vitae mattis leo. Phasellus tristique, sem vitae egestas porttitor, neque mi rutrum nisi, sit amet feugiat neque eros quis purus. Proin sed turpis vitae magna egestas mollis a eget massa. Nam magna orci, accumsan ac luctus quis, egestas a dui. Suspendisse potenti. Aenean vestibulum libero magna, ut egestas erat rutrum porttitor. Vivamus eu suscipit leo. Sed fermentum non leo tempus faucibus. Aenean dolor turpis, finibus in imperdiet ac, viverra volutpat risus. Praesent quis auctor mauris.';
        $region->img_url        = 'PLACEHOLDER';
        $region->save();

        $region = new Region();
        $region->name           = 'Costa Rica';
        $region->description    = 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Maecenas malesuada, metus eget condimentum consectetur, purus velit aliquam quam, ac ullamcorper tellus nisl vulputate nibh. Maecenas iaculis, justo id varius pellentesque, nunc tortor dapibus sem, ut malesuada leo diam in urna. Donec nibh magna, blandit eget magna hendrerit, tincidunt mollis magna. Proin dapibus massa a nibh ultrices tempus. Praesent sed fringilla massa. Quisque quis lobortis ipsum. Suspendisse ut ex nisl. Cras sit amet urna tempor, porttitor libero ac, rhoncus libero. Etiam nec purus at turpis semper aliquet vitae quis quam. Morbi sodales urna vel neque vestibulum placerat.
                                   Quisque aliquet, nisl quis sagittis porta, nibh ipsum sagittis leo, eu aliquet orci sapien ut velit. Praesent vel condimentum nisi, ac tristique mi. Sed eu nulla accumsan, commodo tortor at, egestas mi. Proin eros sem, porta nec accumsan gravida, imperdiet non tellus. Sed egestas, ex sed tristique finibus, arcu diam ultricies ligula, eu aliquet tortor ex quis tortor. Curabitur vitae mattis leo. Phasellus tristique, sem vitae egestas porttitor, neque mi rutrum nisi, sit amet feugiat neque eros quis purus. Proin sed turpis vitae magna egestas mollis a eget massa. Nam magna orci, accumsan ac luctus quis, egestas a dui. Suspendisse potenti. Aenean vestibulum libero magna, ut egestas erat rutrum porttitor. Vivamus eu suscipit leo. Sed fermentum non leo tempus faucibus. Aenean dolor turpis, finibus in imperdiet ac, viverra volutpat risus. Praesent quis auctor mauris.';
        $region->img_url        = 'PLACEHOLDER';
        $region->save();

        $region = new Region();
        $region->name           = 'Sumatra';
        $region->description    = 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Maecenas malesuada, metus eget condimentum consectetur, purus velit aliquam quam, ac ullamcorper tellus nisl vulputate nibh. Maecenas iaculis, justo id varius pellentesque, nunc tortor dapibus sem, ut malesuada leo diam in urna. Donec nibh magna, blandit eget magna hendrerit, tincidunt mollis magna. Proin dapibus massa a nibh ultrices tempus. Praesent sed fringilla massa. Quisque quis lobortis ipsum. Suspendisse ut ex nisl. Cras sit amet urna tempor, porttitor libero ac, rhoncus libero. Etiam nec purus at turpis semper aliquet vitae quis quam. Morbi sodales urna vel neque vestibulum placerat.
                                   Quisque aliquet, nisl quis sagittis porta, nibh ipsum sagittis leo, eu aliquet orci sapien ut velit. Praesent vel condimentum nisi, ac tristique mi. Sed eu nulla accumsan, commodo tortor at, egestas mi. Proin eros sem, porta nec accumsan gravida, imperdiet non tellus. Sed egestas, ex sed tristique finibus, arcu diam ultricies ligula, eu aliquet tortor ex quis tortor. Curabitur vitae mattis leo. Phasellus tristique, sem vitae egestas porttitor, neque mi rutrum nisi, sit amet feugiat neque eros quis purus. Proin sed turpis vitae magna egestas mollis a eget massa. Nam magna orci, accumsan ac luctus quis, egestas a dui. Suspendisse potenti. Aenean vestibulum libero magna, ut egestas erat rutrum porttitor. Vivamus eu suscipit leo. Sed fermentum non leo tempus faucibus. Aenean dolor turpis, finibus in imperdiet ac, viverra volutpat risus. Praesent quis auctor mauris.';
        $region->img_url        = 'PLACEHOLDER';
        $region->save();

        $region = new Region();
        $region->name           = 'Colombia';
        $region->description    = 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Maecenas malesuada, metus eget condimentum consectetur, purus velit aliquam quam, ac ullamcorper tellus nisl vulputate nibh. Maecenas iaculis, justo id varius pellentesque, nunc tortor dapibus sem, ut malesuada leo diam in urna. Donec nibh magna, blandit eget magna hendrerit, tincidunt mollis magna. Proin dapibus massa a nibh ultrices tempus. Praesent sed fringilla massa. Quisque quis lobortis ipsum. Suspendisse ut ex nisl. Cras sit amet urna tempor, porttitor libero ac, rhoncus libero. Etiam nec purus at turpis semper aliquet vitae quis quam. Morbi sodales urna vel neque vestibulum placerat.
                                   Quisque aliquet, nisl quis sagittis porta, nibh ipsum sagittis leo, eu aliquet orci sapien ut velit. Praesent vel condimentum nisi, ac tristique mi. Sed eu nulla accumsan, commodo tortor at, egestas mi. Proin eros sem, porta nec accumsan gravida, imperdiet non tellus. Sed egestas, ex sed tristique finibus, arcu diam ultricies ligula, eu aliquet tortor ex quis tortor. Curabitur vitae mattis leo. Phasellus tristique, sem vitae egestas porttitor, neque mi rutrum nisi, sit amet feugiat neque eros quis purus. Proin sed turpis vitae magna egestas mollis a eget massa. Nam magna orci, accumsan ac luctus quis, egestas a dui. Suspendisse potenti. Aenean vestibulum libero magna, ut egestas erat rutrum porttitor. Vivamus eu suscipit leo. Sed fermentum non leo tempus faucibus. Aenean dolor turpis, finibus in imperdiet ac, viverra volutpat risus. Praesent quis auctor mauris.';
        $region->img_url        = 'PLACEHOLDER';
        $region->save();

        $region = new Region();
        $region->name           = 'Guatemala';
        $region->description    = 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Maecenas malesuada, metus eget condimentum consectetur, purus velit aliquam quam, ac ullamcorper tellus nisl vulputate nibh. Maecenas iaculis, justo id varius pellentesque, nunc tortor dapibus sem, ut malesuada leo diam in urna. Donec nibh magna, blandit eget magna hendrerit, tincidunt mollis magna. Proin dapibus massa a nibh ultrices tempus. Praesent sed fringilla massa. Quisque quis lobortis ipsum. Suspendisse ut ex nisl. Cras sit amet urna tempor, porttitor libero ac, rhoncus libero. Etiam nec purus at turpis semper aliquet vitae quis quam. Morbi sodales urna vel neque vestibulum placerat.
                                   Quisque aliquet, nisl quis sagittis porta, nibh ipsum sagittis leo, eu aliquet orci sapien ut velit. Praesent vel condimentum nisi, ac tristique mi. Sed eu nulla accumsan, commodo tortor at, egestas mi. Proin eros sem, porta nec accumsan gravida, imperdiet non tellus. Sed egestas, ex sed tristique finibus, arcu diam ultricies ligula, eu aliquet tortor ex quis tortor. Curabitur vitae mattis leo. Phasellus tristique, sem vitae egestas porttitor, neque mi rutrum nisi, sit amet feugiat neque eros quis purus. Proin sed turpis vitae magna egestas mollis a eget massa. Nam magna orci, accumsan ac luctus quis, egestas a dui. Suspendisse potenti. Aenean vestibulum libero magna, ut egestas erat rutrum porttitor. Vivamus eu suscipit leo. Sed fermentum non leo tempus faucibus. Aenean dolor turpis, finibus in imperdiet ac, viverra volutpat risus. Praesent quis auctor mauris.';
        $region->img_url        = 'PLACEHOLDER';
        $region->save();

        $region = new Region();
        $region->name           = 'Blend';
        $region->description    = 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Maecenas malesuada, metus eget condimentum consectetur, purus velit aliquam quam, ac ullamcorper tellus nisl vulputate nibh. Maecenas iaculis, justo id varius pellentesque, nunc tortor dapibus sem, ut malesuada leo diam in urna. Donec nibh magna, blandit eget magna hendrerit, tincidunt mollis magna. Proin dapibus massa a nibh ultrices tempus. Praesent sed fringilla massa. Quisque quis lobortis ipsum. Suspendisse ut ex nisl. Cras sit amet urna tempor, porttitor libero ac, rhoncus libero. Etiam nec purus at turpis semper aliquet vitae quis quam. Morbi sodales urna vel neque vestibulum placerat.
                                   Quisque aliquet, nisl quis sagittis porta, nibh ipsum sagittis leo, eu aliquet orci sapien ut velit. Praesent vel condimentum nisi, ac tristique mi. Sed eu nulla accumsan, commodo tortor at, egestas mi. Proin eros sem, porta nec accumsan gravida, imperdiet non tellus. Sed egestas, ex sed tristique finibus, arcu diam ultricies ligula, eu aliquet tortor ex quis tortor. Curabitur vitae mattis leo. Phasellus tristique, sem vitae egestas porttitor, neque mi rutrum nisi, sit amet feugiat neque eros quis purus. Proin sed turpis vitae magna egestas mollis a eget massa. Nam magna orci, accumsan ac luctus quis, egestas a dui. Suspendisse potenti. Aenean vestibulum libero magna, ut egestas erat rutrum porttitor. Vivamus eu suscipit leo. Sed fermentum non leo tempus faucibus. Aenean dolor turpis, finibus in imperdiet ac, viverra volutpat risus. Praesent quis auctor mauris.';
        $region->img_url        = 'PLACEHOLDER';
        $region->save();

        $region = new Region();
        $region->name           = 'Other';
        $region->description    = 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Maecenas malesuada, metus eget condimentum consectetur, purus velit aliquam quam, ac ullamcorper tellus nisl vulputate nibh. Maecenas iaculis, justo id varius pellentesque, nunc tortor dapibus sem, ut malesuada leo diam in urna. Donec nibh magna, blandit eget magna hendrerit, tincidunt mollis magna. Proin dapibus massa a nibh ultrices tempus. Praesent sed fringilla massa. Quisque quis lobortis ipsum. Suspendisse ut ex nisl. Cras sit amet urna tempor, porttitor libero ac, rhoncus libero. Etiam nec purus at turpis semper aliquet vitae quis quam. Morbi sodales urna vel neque vestibulum placerat.
                                   Quisque aliquet, nisl quis sagittis porta, nibh ipsum sagittis leo, eu aliquet orci sapien ut velit. Praesent vel condimentum nisi, ac tristique mi. Sed eu nulla accumsan, commodo tortor at, egestas mi. Proin eros sem, porta nec accumsan gravida, imperdiet non tellus. Sed egestas, ex sed tristique finibus, arcu diam ultricies ligula, eu aliquet tortor ex quis tortor. Curabitur vitae mattis leo. Phasellus tristique, sem vitae egestas porttitor, neque mi rutrum nisi, sit amet feugiat neque eros quis purus. Proin sed turpis vitae magna egestas mollis a eget massa. Nam magna orci, accumsan ac luctus quis, egestas a dui. Suspendisse potenti. Aenean vestibulum libero magna, ut egestas erat rutrum porttitor. Vivamus eu suscipit leo. Sed fermentum non leo tempus faucibus. Aenean dolor turpis, finibus in imperdiet ac, viverra volutpat risus. Praesent quis auctor mauris.';
        $region->img_url        = 'PLACEHOLDER';
        $region->save();

	}

}